### ISSUE TITLE
tqdm ncols is incorrect in jupyter

### ISSUE THREAD

**Issue by Legend94rz** [tqdm/tqdm#1440]
- [ ] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [x] visual output bug
- [x] I have visited the [source website], and in particular
  read the [known issues]
- [x] I have searched through the [issue tracker] for duplicates
- [x] I have mentioned version numbers, operating system and
  environment, where applicable:
  ```python
  import tqdm, sys
  print(tqdm.__version__, sys.version, sys.platform)
  ```

```[tasklist]
### Tasks
- [x] Add a draft title or issue reference here
```

[source website]: https://github.com/tqdm/tqdm/
[known issues]: https://github.com/tqdm/tqdm/#faq-and-known-issues
[issue tracker]: https://github.com/tqdm/tqdm/issues?q=

when used in jupyter lab, it seems like that the width of tqdm bar is not calculated correctly.
for example:
```
bar = tqdm(range(100), file=sys.stdout)
for j in bar:
    bar.set_postfix(a=f'a long long long long long long long long long long long long long long long long long long long long long postfix')
    pass
```
gives:
![image](https://user-images.githubusercontent.com/7570644/223645856-e7a7e7dd-9886-43e1-a489-920402f7d6ab.png)
the latter of postfix cannot seen, but there is plenty spaces at right.

However, when I set `ncols=180` for example, it scales the width of progress bar, which looks like:
![image](https://user-images.githubusercontent.com/7570644/223646924-f8341e43-c024-4dc2-8b56-fdf3a8407c75.png)

I have check the output of `_screen_shape_linux`, `_screen_shape_linux(sys.stdout)` gives `(103, 11)`, in which the #column `103` is incorrect in jupyter lab.

some packages I used:
```
import sys
from importlib.metadata import version
import tqdm, sys
print(tqdm.__version__, sys.version, sys.platform)
print("tqdm:", version("tqdm"))
print("jupyterlab:", version("jupyterlab"))
print("ipywidgets:", version("ipywidgets"))
print("comm:", version("comm"))
```
output:
```
4.64.1 3.10.9 | packaged by conda-forge | (main, Feb  2 2023, 20:20:04) [GCC 11.3.0] linux
tqdm: 4.64.1
jupyterlab: 3.6.1
ipywidgets: 8.0.4
comm: 0.1.2
```
