### ISSUE TITLE
submodule inheritance

### ISSUE THREAD

**Issue by casperdcl** [tqdm/tqdm#815]
missing from #800, fixes #790

- [ ] update `gui` inheritance
- [ ] possibly #271 `tqdm.pandas` -> `tqdm.pandas.register(tclass=tqdm.std.tqdm)`? decorator?
- [ ] delayed imports (#176, 2nd issue in #188)
- [ ] future submods as per #248, #258, #278, #227, #609, #158, #94, #279, [TqdmUpTo](https://github.com/tqdm/tqdm#hooks-and-callbacks), https://github.com/tqdm/tqdm/pull/198#issuecomment-421506727 (`simple`), https://github.com/tqdm/tqdm/pull/198#issuecomment-394184136 (`compat`, `perf`, `dload`)
